workflows:
  build-and-export-ios:
    name: Build iOS unsigned (.ipa) for sideloading
    max_build_duration: 30
    environment:
      xcode: latest
      cocoapods: default  # optional; only matters if you use pods
      vars:
        # Since project file isn't obvious, use xcodebuild auto-detect
        # If you know the exact project file and scheme, you can explicitly set them here
        # XCODE_PROJECT: "YourProjectName.xcodeproj"
        # XCODE_SCHEME: "YourSchemeName"
    scripts:
      - name: Clean derived data (optional but helps avoid stale builds)
        script: |
          rm -rf ~/Library/Developer/Xcode/DerivedData/*
      - name: Build for device (unsigned)
        script: |
          set -o pipefail
          # Try building via workspace or project — whichever works
          if [ -f *.xcworkspace ]; then
            xcodebuild build \
              -workspace "$(ls *.xcworkspace | head -n 1)" \
              -scheme "$(ls *.xcworkspace | head -n1 | sed 's/\\.xcworkspace$//')" \
              -configuration Release \
              -sdk iphoneos \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGNING_ALLOWED=NO
          else
            xcodebuild build \
              -project "$(ls *.xcodeproj | head -n 1)" \
              -scheme "$(ls *.xcodeproj | head -n1 | sed 's/\\.xcodeproj$//')" \
              -configuration Release \
              -sdk iphoneos \
              CODE_SIGN_IDENTITY="" \
              CODE_SIGNING_REQUIRED=NO \
              CODE_SIGNING_ALLOWED=NO
          fi
      - name: Package as .ipa
        script: |
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -type d -name "*Release-iphoneos" -maxdepth 3 | tail -n1)/$(ls *.xcodeproj | head -n1 | sed 's/\\.xcodeproj$//').app
          if [ ! -d "$APP_PATH" ]; then
            echo "ERROR: .app not found. Build probably failed."
            exit 1
          fi
          mkdir -p Payload
          cp -R "$APP_PATH" Payload/
          zip -r app.zip Payload
          mv app.zip sweeterdreamsiOS1.ipa
    artifacts:
      - sweeterdreamsiOS1.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - /tmp/xcodebuild_logs/*.log
