workflows:
  build-and-export-ios:
    name: Build iOS unsigned (.ipa) using XcodeGen
    max_build_duration: 30
    environment:
      xcode: latest
    scripts:
      - name: Install XcodeGen
        script: |
          brew install xcodegen

      - name: Generate Xcode project
        script: |
          xcodegen generate
          echo "Generated Xcode project:"
          ls -R .

      - name: Build for device (unsigned)
        script: |
          set -o pipefail

        # Find generated Xcode project (XcodeGen output)
        PROJECT=$(ls *.xcodeproj | head -n 1)
        echo "Detected project: $PROJECT"

        # Infer scheme name from project name
        SCHEME=$(basename "$PROJECT" .xcodeproj)
        echo "Using scheme: $SCHEME"

        xcodebuild \
          -project "$PROJECT" \
          -scheme "$SCHEME" \
          -configuration Release \
          -sdk iphoneos \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          build

      - name: Package as .ipa
        script: |
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -type d -name "*Release-iphoneos" -prune -print 2>/dev/null | head -n 1)

          if [ -z "$APP_PATH" ]; then
            APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -type d -name "*.app" | head -n 1)
          fi

          if [ -z "$APP_PATH" ]; then
            echo "ERROR: .app not found."
            exit 1
          fi

          mkdir Payload
          cp -R "$APP_PATH" Payload/
          zip -r app.zip Payload
          mv app.zip sweeterdreamsiOS1.ipa

    artifacts:
      - sweeterdreamsiOS1.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      # codemagic config
